version: '3.8'

services:
  app:
    build:
      context: ./employee-creator-backend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl --fail http://localhost:8080/actuator/health || exit 1',
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_REACT_APP_API_URL: http://app:8080

volumes:
  mysql-data:
