FROM maven:3.8.4-openjdk-17 as builder

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package -DskipTests

# Second stage: Run the Spring application
FROM eclipse-temurin:17

WORKDIR /app
EXPOSE 8080

COPY --from=builder /app/target/employee-creator-backend.jar .
RUN apt-get update && apt-get install -y inotify-tools

CMD ["java", "-jar", "-Dspring.profiles.active=dev", "-Dspring.devtools.restart.enabled=true", "-Dspring.devtools.livereload.enabled=true", "employee-creator-backend.jar"]
